### ISSUE TITLE
Lid Sleep and Idle Sleep Timer window difficult to read

### ISSUE THREAD

**Issue by ajkblue** [semaja2/InsomniaX#1]
When selecting the timer, e.g. "Disable Lid Sleep for..." or "Disable Idle Sleep for..." (in the latest version 2.1.8) the window that pops up to set the timer is almost impossible to read. I find it _very_ difficult to see any of the words shown on that window, making it very hard to set the timer. This seems to be especially true when "Reduce Transparency" is set in System Preferences. Could the text color be changed to white or the window's background color could be changed to a lighter color?
![screen shot 2016-01-16 at 12 03 32 am](https://cloud.githubusercontent.com/assets/9651939/12371094/0b81815a-bbe5-11e5-85b9-5cbe853dd10d.png)

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
