### ISSUE TITLE
Touchbar support: should turn off when lid is closed

### ISSUE THREAD

**Issue by irvanjitsingh** [semaja2/InsomniaX#11]
Not sure if the API allows for this, but it would be helpful to save power on newer Toucbar Macs. It doesn't seem to be turning off with the display right now. Under normal operation sleeping the laptop triggers it to turn off.

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
