### ISSUE TITLE
States not saved on Sierra!

### ISSUE THREAD

**Issue by besserwisser** [semaja2/InsomniaX#13]
The app is doing exactly what I wanted it to do. But the states are not saved! I checked "Save state on exit", but I have to click on "Disable Lid Sleep"every time I reboot the mac. There are many people around the Internet having the same issue with InsomniaX. 

I am using mac OS 10.12.5 (16F73) with InsomniaX Version 2.1.8 (2.1.8) on a Mac Book Pro 2016.  

Looking forward to a fix! Thanks for the great work!

**Comment by debevv** [comment]
Same here. Actually, it works when the application is closed and reopened, but after system reboot these two settings ("Disable lid sleep" and "Disable idle sleep") are lost

Same app and macos versions as @besserwisser

**Comment by wgdavies** [comment]
Have had the same issue ongoing with El Capitan, 10.11.16, 2015 MacBook Air 13-inch, InsomniaX 2.1.8. Not a big deal but would be nice to be fixed!

**Comment by besserwisser** [comment]
I think this is a big deal. It is totally annoying to activate it every time you close your lid. Especially, if you do this 10 times a day... But I don't see any hope for a fix here. The Developer is not really active on this project :( Maybe we need someone else who can fix this...

**Comment by wgdavies** [comment]
@besserwisser your original post specified this only occurred when you _rebooted_ your Mac, not every time you close/re-open the lid&hellip;? Is this a new issue or are you actually rebooting multiple times per day? 

I am seeing a new issue (after a security update) that I can no longer "Disable Lid Sleep" at all. New Issue coming as soon as I can properly regress and find any workarounds.

**Comment by besserwisser** [comment]
@wgdavies I deleted my comment, it was pointless... I only have to deactivate the lid sleep once a day, when I start my MacBook.

**Comment by junked** [comment]
InsomniaX 2.1.8
Have this issue on Sierra 10.12.6. Still need to re-activate "Disable Lid Sleep" option after reboot.
How to fix it?

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
