### ISSUE TITLE
Feature request: Set battery saver limit

### ISSUE THREAD

**Issue by denverslair** [semaja2/InsomniaX#14]
Hi 
I keep forgetting InsomniaX is running and then find I have a flat battery. 
Please can a battery saver feature be added where you can set a 'percentage battery remaining' limit when InsomniaX then turns off?

Thanks.

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
