### ISSUE TITLE
Insomnia X Not Saving States

### ISSUE THREAD

**Issue by deadzak** [semaja2/InsomniaX#17]
Hello, 

I use insomniaX as work around for remote login using ARD to manage 100 Apple laptops. I have setup a switch in each laptop cart (ancient carts) and am able to login and manage all the laptops. What i noticed is when the laptops are restarted insomniaX does not start back up and I lose connection. I was under the impression that if selected "Start on login" and "Save States on Exit" insomnia would continue to work even when restarted. I am currently using MAC OSX 10.12.6 and the laptops are 2016 Macbook pro's. I am curious if this is glitch and will it be fixed in future builds?

I often have to restart multiple times a day due to applying app updates.

Thanks for your help

Zak

**Comment by gmcouto** [comment]
I am facing the same issue

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
