### ISSUE TITLE
Disable lid sleep not working on 10.13.2

### ISSUE THREAD

**Issue by surenzxx** [semaja2/InsomniaX#19]
When attempting to disable lid sleep, the program asks for my password and I enter it but it doesn't activate. I'm running version 2.1.8 and I installed it by copying into applications folder. I've tried re-installing numerous times but it doesn't fix my issue.

**Comment by Baekalfen** [comment]
See the new readme-file. It has been solved now.

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
