### ISSUE TITLE
Disable lid sleep doesn't work on 10.11.3

### ISSUE THREAD

**Issue by neverfox** [semaja2/InsomniaX#2]
With "Disable lid sleep" engaged, the computer still sleeps if I close the lid or with the manually lock the screen. I'm running 2.1.8, installed through Homebrew Cask.

**Comment by frankhommers** [comment]
Also true for 10.11.4

**Comment by unknownzerx** [comment]
Works for me on 10.11.4, downloaded from the official site.

@neverfox @frankhommers is the kext loaded? See it with `kextstat | grep insomnia`

**Comment by KingMario** [comment]
From my mba, the kext is not loaded, what shall I do? Thanks in advance.

**Comment by neverfox** [comment]
That command prints out nothing for me.

**Comment by KingMario** [comment]
@unknownzerx @neverfox I uninstalled it and reinstalled it, the problem is gone.

**Comment by neverfox** [comment]
Same. After choosing the option, it asked for my password and then the kext was loaded. Was it a change to OS X, because the Insomnia-X version is the same.

**Comment by kamilbrzakala** [comment]
Doesn't work on High Sierra 10.13.3
