### ISSUE TITLE
MacBook sleeps when disconnecting external monitor

### ISSUE THREAD

**Issue by Baekalfen** [semaja2/InsomniaX#21]
It works fine when just using the built-in display.

I had hoped it worked as well, when running with the lid close, and using an external monitor. But when I disconnect the monitor, it goes to sleep after a few seconds.

I'm running macOS 10.13.2.

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
