### ISSUE TITLE
Is the screen supposed to turnoff when the lid is closed

### ISSUE THREAD

**Issue by aristidesfl** [semaja2/InsomniaX#22]
I've disabled lid sleep, but when I close the lid the display turns off. Does this mean the app is not working, or is it normal?

```
Macbook Pro 13' 2017
macOS Sierra 10.12.6 
InsomniaX 10.12.6 
```

**Comment by Baekalfen** [comment]
Try playing some audio for example through iTunes or YouTube. Does it keep playing, then it's working

**Comment by aristidesfl** [comment]
Great idea. It keeps playing even though the screen sleeps! Thank you!
