### ISSUE TITLE
Disable Lid Sleep doesn't work on InsomniaX 2.1.8 on MacOS 10.13.2

### ISSUE THREAD

**Issue by gespinha** [semaja2/InsomniaX#23]
Hi there,

I'm currently running InsomniaX 2.1.8 and noticed the Disable Lid Sleep option is not working on MacOS 10.13.2

I've tried following your "[Installing On OSX 10.12 and afterward](https://github.com/semaja2/InsomniaX#installing-on-osx-1012-and-afterward)" instructions, but they don't work as well.

Is this a known issue? Is there any possible fix?

Thanks!

**Comment by ncasaux** [comment]
Hello,
I confirm the issue.

**Comment by sajangupta-pt** [comment]
same issue, os version 10.13.4.

**Comment by Benjiaming23** [comment]
me too, os version 10.13.4.

**Comment by pbangia** [comment]
Had the same issue - but after following the steps in the readme I had to close InsomniaX, go to Security & Privacy settings, click the lock icon in the bottom left and enter password, then launch InsomniaX again and it worked.

**Comment by rambodrahmani** [comment]
On macOS High Sierra 10.13.6 I had to disable SIP to be able to get Disable Lid Sleep to work (InsomniaX latest version). Just restart your mac, hold down Command-R to boot into the Recovery System. Click the Utilities menu and select Terminal. Type csrutil disable and press return. Close the Terminal app. Click the apple menu and select Restart.

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
