### ISSUE TITLE
Create new release with security fix only

### ISSUE THREAD

**Issue by notDavid** [semaja2/InsomniaX#24]
Hi there @semaja2 ,

many people running InsomniaX will not be aware of the [security fix](https://github.com/semaja2/InsomniaX#security-fix), so please consider releasing a new version of InsomniaX with only the fix implemented - that way it will also be available in for example the [Homebrew Cask.](https://github.com/caskroom/homebrew-cask/blob/master/Casks/insomniax.rb)

Thank you :)

**Comment by gfairchild** [comment]
Completely agreed.

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
