### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by Lythimus** [semaja2/InsomniaX#29]
I've tried to pass several arguments into InsomniaX via command line to set values on start without interaction required. If this is supported, I can't figure out what the parameters names are. Could you add basic command line support to at least set 'Disable Lid Sleep' and 'Disable Idle Sleep' values on start? If I had more MacOS dev experience I would just make a pull request myself.

This request is similar, but more general than [Provides the API to know Lid closed](https://github.com/semaja2/InsomniaX/issues/15).

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
