### ISSUE TITLE
An option to avoid the prompt when quitting.

### ISSUE THREAD

**Issue by unknownzerx** [semaja2/InsomniaX#3]
When quitting, there will be a prompt of 'Idle/Lid Sleep will be returned to normal if you continue'. I would like there is no prompt.

I tried to DIY it by commenting out some lines in function `quitInsomniaX`. However, for unknown reason, my custom built version cannot restore state when started again.

**Comment by niki-timofe** [comment]
+1

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
