### ISSUE TITLE
Mac Mojave 10.14.3 option [Disable Lid Sleep] is not available

### ISSUE THREAD

**Issue by huoleihu** [semaja2/InsomniaX#30]
Update the latest Mac operating system(10.14.3),The  [Disable Lid Sleep]  option was found to be unavailable,no response after clicking。

**Comment by hilyin** [comment]
yep. uninstalled because it doesn't work.

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
