### ISSUE TITLE
InsomniaX System Slow down on MacOS Mojave READ!

### ISSUE THREAD

**Issue by retrorick21** [semaja2/InsomniaX#31]
For 6 months I've been using InsomniaX and I noticed a complete system lockup doing simple things like opening a Finder window or clicking the 'x' of windows. Simple things completely locked up my MacBook Pro running Mac OS Mojave. 

I was really frustrated about about to wipe my machine for the second time this year, I thought my machine was done for good because it just felt slow as molasses. I decided to single out each app and see if there was an improvement, when I got to deleting InsomniaX I hesitated because it's such a lightweight tool, how could it cause problems like constant beach ball...it was almost as if my machine was using 80% of it's resources when this app was open, but Activity Monitor never pointed to anything that I could pin point. 

Once I closed InsomniaX and deleted it from my system it was like my computer was brought back to life, it functions like it did the day I bought it. I'm hoping this bug report helps whoever finds it because I was at a loss for what happened to my MacBook Pro and was about to spend more money just to not have to deal with the significant slowdown this app caused. It's useful but too buggy in it's current state and at this point it seems like abandon ware as it's last update was 3 years ago.

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
