### ISSUE TITLE
Freezes with power plug-in

### ISSUE THREAD

**Issue by Umiiii** [semaja2/InsomniaX#34]
MacBook Pro (15-inch, 2019)
10.14.5
InsomniaX 2.1.8

Disable Lid Sleep & Idle Sleep, closed lid, and external monitor.

Power plug-off and power plug-in, then the whole system or currently running foreground application would freeze for a while (~30s), then a charge sound effect plays and unfreeze.

Happened for 15-inch,2015 and 2019, not sure whether to check out the problem.

Also: click the InsomniaX icon on the status bar cause freeze for a while.

<img width="145" alt="屏幕快照 2019-06-13 下午10 54 32" src="https://user-images.githubusercontent.com/29030474/59443293-4c39b180-8e2e-11e9-9523-d6932ed41412.png">

**Comment by darkfader** [comment]
I have the exact same problem.
Perhaps "syscall_extension_issue failed: 22" or "stalling for detach from AppleSMC" have something to do with it?
Also, the update check fails to resolve.

**Comment by Umiiii** [comment]
> I have the exact same problem.
> Perhaps "syscall_extension_issue failed: 22" or "stalling for detach from AppleSMC" have something to do with it?
> Also, the update check fails to resolve.

I use NoSleep as an alternative solution.

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
