### ISSUE TITLE
Disable Lid/Idle sleep when on battery?

### ISSUE THREAD

**Issue by buu700** [semaja2/InsomniaX#4]
It's pretty uncommon (the exception rather than the rule) that I ever want my laptop to automatically sleep even when I'm on battery, so it'd be more convenient for me to manually put it to sleep in those odd instances than to have to manually toggle InsomniaX's settings every other time.

Any chance of "Disable Lid/Idle sleep when on battery" being added as on option to go along with the existing "Disable Lid/Idle sleep when on AC"?

Thanks!

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
