### ISSUE TITLE
InsomniaX randomly fails to keep MacBook Air awake with lid closed

### ISSUE THREAD

**Issue by ghost** [semaja2/InsomniaX#5]
I have noticed that sometimes when I close the lid of my MacBook Air with lid sleep disabled, it goes to sleep anyway. I wonder if the fact that I have an external monitor connected complicates matters, even though I turn off the external monitor before closing the lid.

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
