### ISSUE TITLE
Feature request: disable lid sleep when external display detected

### ISSUE THREAD

**Issue by corymayer** [semaja2/InsomniaX#6]
This would make it easier to disable when you're done using it instead of having to set a timer.

**Comment by abhijit-paul** [comment]
I'm taking a look at implementing this feature. I too want this.

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
