### ISSUE TITLE
Lid sleep only works once on OS 10.9.5

### ISSUE THREAD

**Issue by imbrou** [semaja2/InsomniaX#8]
Hey !

Thank you for InsomniaX, it’s just wonderful !
I’m having an issue with lid sleep: disabling it works only once on my computer.

**To reproduce the bug:**
- Open InsomniaX
- Disable Lid Sleep
- Close laptop (won’t sleep)
- Open laptop

Then I get stuck in a strange state where the menubar icon still shows the disabled lid, but if I close again my laptop, it will just sleep as if InsomniaX was disabled.

Trying to re-enable lid sleep has no effect. The menubar icon freezes (blue background) for ~1 second, then comes back on the same state again (= lid sleep disabled: 
![bildschirmfoto 2016-10-26 um 12 06 59](https://cloud.githubusercontent.com/assets/12932751/19722287/4b64eda4-9b76-11e6-856b-ab0f0ea2ef00.png)). It looks like InsomniaX is stuck in this state.

Hope it helps, I'm still available for additional information, and in the wait,
Have a wonderful day ! :-)

[**system-report.zip**](https://github.com/semaja2/InsomniaX/files/552988/system-report.zip)

Brou

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
