### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by SchwiftyLife** [semaja2/InsomniaX#9]
when i run insomnia x everything slows down for some moments and freezes ,and it have some compatibility issues with better touch tool and bartender too , better touch tool force touch slows down and freezes the system and bartender too. please somebody care for this wonderful app and fix it . the app is worth it :(

**Comment by retrorick21** [comment]
The problems gets worse with MacOS Mojave, my system was completely unresponsive for 6 months until I narrowed it down to this one 300 KB program causing all of my issues. I don't know why I didn't put 2 and 2 together sooner, but now that I've deleted the app my machine Is super fast again and I no longer have random beach ball hangups for every little thing I try to do on my Mac.

**Comment by benapetr** [comment]
Yes, unfortunatelly I also had to remove it completely to remediate the problem.

**Comment by semaja2** [comment]
InsomniaX is abandonware (for a considerable time now) please look at alternative as no updates will be provided on this repo as no maintainers have been found after 4 years on github
